// Notification
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";
export const NOTIFICATION_WARN = "NOTIFICATION_WARN";
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";
export const NOTIFICATION_DEFAULT = "NOTIFICATION_DEFAULT";
export const NOTIFICATION_DARK = "NOTIFICATION_DARK";